# Add 'type/ci-workflow-env' label for changes to tooling, config, or env files
type/ci-workflow-env:
  - '.github/**/*'
  - '.vscode/**/*'
  - .editorconfig
  - .gitignore
  - .gitattributes
  - .nvmrc
  - .npmrc

# Add 'type/dependencies' label for changes to package.json or pnpm-lock.yaml files
type/dependencies:
  - '**/package.json'
  - '**/pnpm-lock.yaml'

# Add 'documentation' label for changes to *.md files not in the .github folder
type/documentation:
  - any: ['LICENSE', '**/*.md', '!.github/**/*']
