# Add 'type/ci-workflow-env' label for changes to tooling, config, or env files
type/ci-workflow-env:
  - '.github/**/*'
  - '.vscode/**/*'
  - .editorconfig
  - .gitignore
  - .gitattributes
  - .pylintrc

# Add 'type/dependencies' label for changes to requirements.txt
type/dependencies:
  - '**/requirements.txt'

# Add 'documentation' label for changes to *.md files not in the .github folder
type/documentation:
  - any: ['LICENSE', '**/*.md', '!.github/**/*']
