# Add the 'status/triage' label for all new PRs
status/triage:
- '*'

# Add 'type/ci-workflow-env' label for changes to .github folder or other supporting files
type/ci-workflow-env:
- '.github/**/*'
- '.vscode/**/*'
- '.editorconfig'
- '.pylintrc'
- '.gitignore'
- '.gitattributes'

# Add 'type/dependencies' label for changes to requirements.txt
type/dependencies:
- '**/requirements.txt'

# Add 'docs' label for changes to *.md files not in the .github folder
type/docs:
- any: ['LICENSE', '**/*.md', '!.github/**/*']
