---
name: Pylint

on:
  push:
    branches:
      - main

jobs:
  pylint:
    name: 🔧 Clean up with pylint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code from GitHub
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint pylint-exit
    - name: Analyzing the code with pylint
      run: |
        pylint $(git ls-files '*.py') || pylint-exit $?
